### ISSUE TITLE
Calorie store icon appears as purple box as of 1.48

### ISSUE THREAD

**Issue by AZed** [zeobviouslyfakeacc/HungerRevamped#2] opened 2019-05-14 20:01 UTC
See attached screenshot.
![The Long Dark Screenshot 2019 05 14](https://user-images.githubusercontent.com/115827/57728269-8c581980-7661-11e9-9068-629e4d5583cf.png)

**Comment by zeobviouslyfakeacc** [comment] 2019-05-15 00:27
Hi, thank you very much for reporting this issue!

I've already fixed this issue (by simply selecting a different, similar icon 😄), but I still want to do a bit more testing to make sure everything's actually working as intended before I release the next version of HungerRevamped.

I unfortunately don't have much time for modding at the moment, so it may take a bit longer for things to get updated than you're used to. Also, the suddenly quite real possibility of Hinterland killing off modding for good doesn't exactly help with motivation, either 😅

**Comment by AZed** [comment] 2019-05-15 15:50
I certainly agree that real life comes first, so I hope everything works out for you and gives you the time you need.

**Comment by zeobviouslyfakeacc** [comment] 2019-06-01 23:04
Should now be fixed as of [version 1.5](https://github.com/zeobviouslyfakeacc/HungerRevamped/releases/tag/v1.5) 😄
Sorry about the longer-than-usual delay!

**Closed as completed by zeobviouslyfakeacc** 2019-06-01 23:04 UTC
Labels: bug
